### ISSUE TITLE
Modals are not working 

### ISSUE THREAD

**Issue by Alvai** [amandeepmittal/gatsby-starter-ceevee#7]
Hi,

The modals are not working, i tried to remove the comments but now they are displayed all the time and it breaks the portfolio.

I'll try to fix it but i don't know how they are working.

Can somebody check please ?

**Comment by rperez2021** [comment]
You are correct modals are currently broken. When I come up with a solution I will post it here.

**Comment by Elohina** [comment]
Hi @Alvai here https://github.com/amandeepmittal/gatsby-starter-ceevee/pull/11 there is a solution for modal's issue.
